export const projects = [
  {
    id: 0,
    title: "Airbnb Clone",
    description: "Minimal Airbnb UI clone",
    image: "/project-img/airbnb.png",
    tags: ["react", "mui", "firebase"],
    visit: "https://airbnb-clone-v1-stark.web.app/",
  },
  {
    id: 1,
    title: "Facebook Clone",
    description: "Facebook homepage UI",
    image: "/project-img/facebook.png",
    tags: ["react", "vite", "firebase", "mui"],
    visit: "https://facebook-clone-v1-stark.web.app/",
  },
  {
    id: 2,
    title: "Gmail Clone",
    description: "Gmail UI",
    image: "/project-img/gmail.png",
    tags: ["mui", "firebase", "react", "redux"],
    visit: "https://clone-v1-61b7f.web.app/",
  },
  {
    id: 3,
    title: "Crypto Clone",
    description: "Web3.0 app clone",
    image: "/project-img/krypt.png",
    tags: [
      "react",
      "vite",
      "ethers",
      "react-icons",
      "solidity",
      "hardhat",
      "tailwindcss",
    ],
    visit: "https://kind-noyce-5693ab.netlify.app/",
  },
  {
    id: 4,
    title: "Metaverse Chat",
    description: "Chat app in web3.0 on desktop",
    image: "/project-img/metaverse.png",
    tags: ["next", "moralis", "walletconnect", "tailwindcss"],
    visit: "https://metaverse-v1-0.vercel.app/",
  },
  {
    id: 5,
    title: "Netflix Clone",
    description: "Netflix UI. Makes API call to movie endpoint",
    image: "/project-img/netflix.png",
    tags: ["react", "axios", "firebase"],
    visit: "https://netflix-clone-v1-stark.web.app/",
  },
  {
    id: 6,
    title: "Signal Clone",
    description: "React native signal app clone",
    image: "/project-img/signal_native.png",
    tags: ["react-native", "expo", "firebase"],
    visit: "https://signal-native-clone-v1.web.app/",
  },
  {
    id: 7,
    title: "Slack Clone",
    description: "Slack UI",
    image: "/project-img/slack.png",
    tags: ["react", "mui", "firebase", "redux", "styled-components"],
    visit: "https://slack-clone-v1-stark.web.app/",
  },
  {
    id: 8,
    title: "Twitter Clone",
    description: "Twitter UI",
    image: "/project-img/twitter.png",
    tags: ["react", "mui", "firebase", "react-flip-move"],
    visit: "https://twitter-clone-v1-stark.web.app/",
  },
  {
    id: 9,
    title: "Whatsapp Clone",
    description: "Whatsapp chat clone",
    image: "/project-img/whatsapp.png",
    tags: ["react", "mui", "firebase", "react-router-dom"],
    visit: "https://whatsapp-clone-99921.web.app/",
  },
  {
    id: 10,
    title: "Youtube Clone",
    description: "Youtube homepage",
    image: "/project-img/yt.png",
    tags: ["react", "mui", "firebase"],
    visit: "",
  },
];

export const project = [
  {
    title: "MERN Memories",
    description:
      "Using React, Node.js, Express & MongoDB you'll learn how to build a Full Stack MERN Application - from start to finish. The App is called Memories and it is a simple social media app that allows users to post interesting events that happened in their lives.",
    image: "/project-img/airbnb.png",
    tags: ["Mongo", "Express", "React", "Node"],
    source: "https://google.com",
    visit: "https://google.com",
    id: 0,
  },
  {
    title: "E-Commerce",
    description:
      "While building it you're going to learn many advanced React & JavaScript topics, as well as how to use Stripe for card transactions. On top of that, at the end of the video, you will have this unique and complex webshop app that you will be able to add to your portfolio. And trust me, e-commerce applications are impressive.",
    image: "/images/2.png",
    tags: ["React", "JavaScript"],
    source: "https://google.com",
    visit: "https://google.com",
    id: 1,
  },
  {
    title: "WebRTC App",
    description:
      "This is a code repository for the corresponding YouTube video. In this tutorial, we're going to build and deploy a React Video Chat Application using WebRTC.",
    image: "/images/3.jpg",
    tags: ["React", "WebRTC"],
    source: "https://google.com",
    visit: "https://google.com",
    id: 2,
  },
  {
    title: "Unichat",
    description:
      "This is a code repository for the corresponding video tutorial. In this video, we will create a full Realtime Chat Application",
    image: "/images/4.jpg",
    tags: ["React", "ChatEngine", "Firebase"],
    source: "https://google.com",
    visit: "https://google.com",
    id: 3,
  },
];

export const TimeLineData = [
  { year: 2017, text: "Started my journey" },
  { year: 2018, text: "Worked as a freelance developer" },
  { year: 2019, text: "Founded JavaScript Mastery" },
  { year: 2020, text: "Shared my projects with the world" },
  { year: 2021, text: "Started my own platform" },
];
